In [2]:
import numpy as np
# Q1
arr1 = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr1)
arr_add = arr1 + 2
print("After adding 2:", arr_add)

arr_mult = arr1 * 3
print("After multiplying by 3:", arr_mult)

arr_div = arr1 / 2
print("After dividing by 2:", arr_div)


Original Array: [1 2 3 4 5]
After adding 2: [3 4 5 6 7]
After multiplying by 3: [ 3  6  9 12 15]
After dividing by 2: [0.5 1.  1.5 2.  2.5]


In [3]:
import numpy as np
# Q2
arr2 = np.array([1, 2, 3, 6, 4, 5])
arr_rev = arr2[::-1]
print("Reversed array:", arr_rev)

def most_frequent(arr):
    vals, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_freq_val = vals[np.argmax(counts)]
    indices = np.where(arr == most_freq_val)[0]
    return most_freq_val, indices

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])

val_x, indices_x = most_frequent(x)
print(f"Most frequent value in x: {val_x}, Indices: {indices_x}")

val_y, indices_y = most_frequent(y)
print(f"Most frequent value in y: {val_y}, Indices: {indices_y}")

Reversed array: [5 4 6 3 2 1]
Most frequent value in x: 1, Indices: [0 5 7 8 9]
Most frequent value in y: 1, Indices: [0 1 2]


In [4]:
import numpy as np
# Q3
arr3 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Element at 1st row, 2nd column:", arr3[0, 1])
print("Element at 3rd row, 1st column:", arr3[2, 0])

Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


In [7]:
import numpy as np
# Q4
my_name_arr = np.linspace(10, 100, 25)
print("My Name Array:", my_name_arr)

print("Dimensions:", my_name_arr.ndim)
print("Shape:", my_name_arr.shape)
print("Total elements:", my_name_arr.size)
print("Data type:", my_name_arr.dtype)
print("Total bytes:", my_name_arr.nbytes)

transposed_arr = my_name_arr.reshape(25, 1)
print("Transposed using reshape():\n", transposed_arr)

print("Using T attribute:", my_name_arr.T)

My Name Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transposed using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T attribute: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [1]:
import numpy as np
# Q5
ucs420_myname = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Original 2D array:\n", ucs420_myname)
print("Mean:", np.mean(ucs420_myname))
print("Median:", np.median(ucs420_myname))
print("Max:", np.max(ucs420_myname))
print("Min:", np.min(ucs420_myname))
print("Unique elements:", np.unique(ucs420_myname))
reshaped_ucs420_myname = ucs420_myname.reshape(4, 3)
print("Reshaped to 4x3:\n", reshaped_ucs420_myname)
resized_ucs420_myname = np.resize(ucs420_myname, (2, 3))
print("Resized to 2x3:\n", resized_ucs420_myname)

Original 2D array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped to 4x3:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized to 2x3:
 [[10 20 30]
 [40 50 60]]
